In [33]:

p=[0,1,5,8,9,10,17,17,20,24,30]
n = 4
def Cut_Rod(p,n):
    if n==0:
        return 0
    r_arr = [n+1]*10
    maximum = 0
    index=0
    
    for i in range(1,n+1):
        r_arr[i] = p[i] + Cut_Rod(p,n-i)
        
        if r_arr[i] > maximum:
            maximum = r_arr[i]
            index = i
            
    print("in",index,maximum)
    return maximum
        
    
    
        
Cut_Rod(p,8)
    
    
    


in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 13
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 6 17
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 13
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 1 18
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 13
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 6 17
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 13
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 10
in 1 1
in 2 5
in 1 1
in 3 8
in 1 1
in 2 5
in 1 1
in 2 22


22

In [2]:
import numpy
def LCS(arr1,arr2):
    arr1 = "0"+arr1
    arr2="1" + arr2
    len1=len(arr1)
    len2=len(arr2)
    print(len1,len2)
    arr_mem=numpy.zeros((len1,len2))

    for i in range(len1-1):
        
        for j in range(len2-1):
            arr_mem[i+1][j+1] = max(arr_mem[i+1][j],arr_mem[i,j+1])
            if arr1[i+1] == arr2[j+1]:                
                arr_mem[i+1][j+1] += 1
                print(arr1[i+1],arr2[j+1])
    print("nilay")
    print(arr_mem)
    
arr1 = str("xmjyau")
arr2 = str("mzjawxu")
LCS(arr1,arr2)

7 8
x x
m m
j j
a a
u u
nilay
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 3. 3. 3. 3.]
 [0. 1. 1. 2. 3. 3. 3. 4.]]


In [19]:
def LCS_rec(X,Y,m,n):
    if m==0 or n==0:
        return 0
    
    if X[m-1]==Y[n-1]:
        return LCS_rec(X,Y,m-1,n-1)+1
    
    return max(LCS_rec(X,Y,m-1,n),LCS_rec(X,Y,m,n-1))
    
LCS_rec(arr1,arr2,len(arr1),len(arr2))  
    
    

4

In [30]:
def LCS_rec(X,Y,Z,m,n,k):
    if m==0 or n==0 or k==0:
        return 0
    
    if X[m-1]==Y[n-1] and X[m-1]==Z[k-1]:
        return LCS_rec(X,Y,Z,m-1,n-1,k-1)+1
    
    return max(LCS_rec(X,Y,Z,m-1,n,k),LCS_rec(X,Y,Z,m,n-1,k),LCS_rec(X,Y,Z,m,n,k-1))

LCS_rec(arr1,arr2,arr3,len(arr1),len(arr2),len(arr3))  

3

In [35]:
def LC_sub(X,Y):
    arr_last=[]
    arr=[]
    
    i=0
    j=0
    
    while i< len(X):
        added = False
        while j<len(Y):
            
            if X[i]==Y[j]:                
                arr.append(X[i])
                i+=1
                j+=1
                added = True
            else:
                j+=1
                
        arr_last.append(arr)
        
    print(arr_last)
    

X="ABABC"
Y="BABCA"

LC_sub(X,Y)

IndexError: string index out of range