In [9]:
def fibo_rec(n):
    
    if n<=1:
        return 1
    
    return fibo_rec(n-1) +fibo_rec(n-2)

fibo_rec(6) 
    

13

In [15]:
f=[1]*300

def fibo_dp(n):
    
    for i in range(2,n+1):
        
        f[i] = f[i-1] + f[i-2]
    return f[n]
   
fibo_dp(6)


13

In [19]:
def fact_rec(n):
    
    if n<=1:
        return 1
    
    return n*fact_rec(n-1)
    
    
fact_rec(5)    
    

120

In [28]:
f=[1]*300
f[0]=1
f[1]=1
def fact_dp(n):
    
    for i in range(2,n+1):
        f[i] = i*f[i-1]
    return f[n]
fact_dp(5)

120

In [54]:
#find path
import numpy as np
cost= [ [1, 2, 3], 
        [4, 8, 2], 
        [1, 5, 3] ] 

def find_path(n,m):
    r=len(cost)
    c=len(cost[0])
    mem = np.zeros((r,c))
    mem[0][0]=cost[0][0]
    print(mem)
    for i in range(1,r):
        mem[i][0] = cost[i][0] + mem[i-1][0] 
        
    for j in range(1,c):
        mem[0][j] = cost[0][j] + mem[0][j-1] 
    print(mem)
    for i in range(1,n+1):        
        for j in range(1,m+1):            
            mem[i][j] = cost[i][j] + min(mem[i-1][j],mem[i][j-1],mem[i-1][j-1])
    print(mem)
    print(mem[n][m])     
    

find_path(2,2)


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 3. 6.]
 [5. 0. 0.]
 [6. 0. 0.]]
[[ 1.  3.  6.]
 [ 5.  9.  5.]
 [ 6. 10.  8.]]
8.0


In [60]:
def find_path_rec(n,m):
    
    if n<0 or m<0:
        return 10000
    if n==0 and m==0:
        return cost[0][0]
    if n == 0:        
        return cost[n][m] + find_path_rec(n,m-1)
    if m == 0:        
        return cost[n][m] + find_path_rec(n-1,m)
    
    return cost[n][m] + min(find_path_rec(n-1,m),find_path_rec(n,m-1),find_path_rec(n-1,m-1))
    
find_path_rec(2,2)  
    
    
    

8

In [72]:
def LCS(arr1,arr2):
    
    mem = np.zeros((len(arr1),len(arr2)))
    
    for i in range(len(arr1)):
        
        for j in range(len(arr2)):           
            if i==0 and j==0:
                mem[i][j] = 0
            elif i==0:
                mem[i][j] = mem[i][j-1]
            elif j==0:
                mem[i][j] = mem[i-1][j]
            else:
                mem[i][j] = max(mem[i-1][j],mem[i][j-1])                
            if arr1[i] == arr2[j]:   
                print(i,j)
                mem[i][j] += 1
    print(mem)    
    return mem[-1][-1]          
    
arr1="acbgh"
arr2="cdg"

LCS(arr1,arr2)
    
    
    

1 0
3 2
[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 2.]
 [1. 1. 2.]]


2.0

In [ ]:
def LCS